### ISSUE TITLE
Page is not found

### ISSUE THREAD

**Issue by mkcgphy** [vigneshr1236/PCF-WebAPI-crud#1]
While I am trying to build component and updating the entity I am not getting the Xrm.Page object in code. Please suggest

**Comment by vigneshr1236** [comment]
You can use the context WebApi interface exposed by the pcf for updating the entity. Take a look at the code in the index.ts file in this repo. Xrm.page is deprecated.

**Comment by mkcgphy** [comment]
> You can use the context WebApi interface exposed by the pcf for updating the entity. Take a look at the code in the index.ts file in this repo. Xrm.page is deprecated.

Thanks Vignesh, Is it possible to make custom action call somehow as well ?

**Comment by vigneshr1236** [comment]
A friend of mine has done an example of calling a custom action. Let me check with him if I could get you the code he has used to achieve it.

You can refer the below link for now 
https://powerusers.microsoft.com/t5/PowerApps-component-framework/Calling-a-Custom-Action/m-p/320651#M576
